development:
  secret_key_base: 3b83d474dcf1c2f5c176650e3e80b9d0770e7ff64f87dac60a42f4f4be65819ef93704aa39d4e74904ade8307f4fa1b93c8c815fcd7cd51a712e6d3f8aa2bb8b
  google_client_id: 157456463524-mihqgaod6il11it64f4udls3fe7o2lst.apps.googleusercontent.com
  google_client_secret: icGvA2chLGmmkxOcTdXcbfHk

test:
  secret_key_base: here_goes_my_secret_key_base

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>